### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by Skyost**
Added an alternative SVG preprocessor to usvg : scour. It is used by a lot of people (including Inkscape) and is a lot easier to use : `scour -i input.svg -o output.svg`.

### CODE REVIEW

**Comment by dnfield** [comment]
That sounds good, one important question is whether scour will add or remove CSS.  This library doesn't support `<style>` elements, and one of the things that `usvg` does is to help remove those.  Is that the case with scour?

**Comment by Skyost** [comment]
Yes absolutely. It converts style attributes into svg attributes :wink:

**Comment by dnfield** [comment]
Thanks!

**Comment by Skyost** [comment]
No problem. If you want a simple example :

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   id="svg8"
   version="1.1"
   viewBox="0 0 135.46666 135.46667"
   height="512"
   width="512">
  <defs
     id="defs2" />
  <metadata
     id="metadata5">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     transform="translate(0,-161.53332)"
     id="layer1">
    <circle
       r="49.22543"
       cy="229.26665"
       cx="67.73333"
       id="path815"
       style="opacity:1;fill:#ff00ff;fill-opacity:1;stroke:#344046;stroke-width:2.64583333;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;paint-order:normal" />
    <rect
       ry="32.978424"
       y="196.28822"
       x="3.3828924"
       height="65.956848"
       width="128.70088"
       id="rect817"
       style="opacity:1;fill:#8c008c;fill-opacity:1;stroke:#344046;stroke-width:2.64583325;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;paint-order:normal" />
  </g>
</svg>
```

Output :

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg id="svg8" width="512" height="512" version="1.1" viewBox="0 0 135.47 135.47" xmlns="http://www.w3.org/2000/svg" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
 <metadata id="metadata5">
  <rdf:RDF>
   <cc:Work rdf:about="">
    <dc:format>image/svg+xml</dc:format>
    <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/>
    <dc:title/>
   </cc:Work>
  </rdf:RDF>
 </metadata>
 <g id="layer1" transform="translate(0 -161.53)" stroke="#344046">
  <circle id="path815" cx="67.733" cy="229.27" r="49.225" fill="#f0f" stroke-width="2.6458" style="paint-order:normal"/>
  <rect id="rect817" x="3.3829" y="196.29" width="128.7" height="65.957" ry="32.978" fill="#8c008c" stroke-width="2.6458" style="paint-order:normal"/>
 </g>
</svg>
```

**Pull request merged**
