### PR TITLE
Fix Issue #317 headers were not passed to http client.

### PR DESCRIPTION
**Pull request by m-oehme**
Using SvgPicture.network with headers was not possible since headers were not passed to the http get request function

fixes https://github.com/dnfield/flutter_svg/issues/317

### CODE REVIEW

**Comment by dnfield** [comment]
I really thought this had been fixed before. 

Can you please add a test covering this?

**Comment by stijnie2210** [comment]
I'm currently running into this issue. Is there any chance this can be merged soon? @dnfield

**Comment by dnfield** [comment]
It needs a test

**Comment by stijnie2210** [comment]
Is there any chance you could pick this up? This seems like a pretty
serious bug since headers are now just useless in the network constructor

**Comment by dnfield** [comment]
Added a test for this and some version bumps.

I realize this would be nice to backport into a stable supported version - that should be doable  if absolutely necessary, but for now I'm putting it into the nullsafety version which requires a pretty recent version of Flutter.

**Comment by dnfield** [comment]
Published as v0.20.0-nullsafety.2

**Pull request merged**
