### PR TITLE
Apply image transform before translate and scale

### PR DESCRIPTION
**Pull request by FeodorFitsner**
Fix https://github.com/dnfield/flutter_svg/issues/788

### CODE REVIEW

**Review by dnfield — COMMENTED** [review]
This makes sense - can you add a test?

**Comment by FeodorFitsner** [comment]
Sure, will give a try. Thanks for looking into that!

**Comment by FeodorFitsner** [comment]
Just added a "golden" test. Is it what you are asking for? I'm not sure why CI is failing with so many failed tests - I did a trivial change. Am I doing something wrong?

**Comment by FeodorFitsner** [comment]
@dnfield Could you please tell me what's wrong with the tests in this PR? I'm really confused as the PR should be affecting `DrawableRasterImage()` method only.

**Comment by dnfield** [comment]
the existing `image.svg` file has a transform on it that I guess wasn't correctly getting applied (does a `translate(1, 1)`). It will have to be updated for this change.

**Comment by FeodorFitsner** [comment]
Alright, here you are!

Are you planning to do a release with these fixes anytime soon? I'd really love to have these changes in the upstream as I'm working on a [package](https://pub.dev/packages/flet) that depends on `flutter_svg` (it's easily crunching SVGs produced by [Matplotlib and Plotly](https://flet.dev/blog/matplotlib-and-plotly-charts)!) and "git" dependencies are not allowed in packages.

**Review by dnfield — APPROVED** [review]

**Comment by dnfield** [comment]
Very cool! I'll try to cut a release soon.

**Comment by dnfield** [comment]
Published in 1.1.6

**Comment by FeodorFitsner** [comment]
Thank you!

**Pull request merged**
