### PR TITLE
Switch to using maybeLocaleOf instead of localeOf

### PR DESCRIPTION
**Pull request by gspencergoog**
See discussion at https://github.com/flutter/flutter/pull/68911

Obv, 1.24.0-8.0.pre hasn't been released yet, but will include the appropriate change when it has been.

### CODE REVIEW

**Comment by gspencergoog** [comment]
cc @dnfield

**Review by dnfield — APPROVED** [review]
LGTM

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Hm.  Looks like dart changed some rules.  I can push a fix up for it and then merge it into this.

**Comment by dnfield** [comment]
Now coveralls is failing? :\

**Comment by gspencergoog** [comment]
`**The specified coverage format is not supported.**` Yeah, that's weird.

**Comment by gspencergoog** [comment]
I just rebased and pushed.  This isn't expected to pass though, until the next dev release, since the requested SDK version doesn't exist yet.

**Comment by gspencergoog** [comment]
I can switch this to a draft PR until then, if you want.

**Comment by dnfield** [comment]
Yeah let's do that, as long as it doesn't block progress upstream.

**Comment by gspencergoog** [comment]
Hmm. I tried re-running this now that 1.24.0-10.2.pre is out in dev (and beta), and it fails on Stable.  Is that expected? It also still fails coveralls, but that seems like a CI problem.

**Comment by gspencergoog** [comment]
OK, @dnfield trying again now that the pubspec has advanced the Flutter version.

**Comment by gspencergoog** [comment]
OK, so maybe I just need to make this change on the nullsafety branch? Seems like the master branch for `flutter_svg` must be failing for all PRs right now, since this change doesn't modify the `pubspec.yaml` anymore.

**Comment by dnfield** [comment]
Coveralls is sometimes failing for reasons I don't understand, this change LGTM and should be fine to land as is.

**Pull request merged**
